### ISSUE TITLE
Not an issue, feature request (new to GitHub)

### ISSUE THREAD

**Issue by F2GD** [fedorcomander/kkc#2]
Hey, I was wondering if you could do dragonlink configuration using a kkc, would it be possible to make a configurator for it as the modules don't have a screen or dpad so you can't edit settings without a computer

**Comment by fedorcomander** [comment]
1. does it have usb?
2. any protocol format available?

**Comment by F2GD** [comment]
It has a micro USB port on it, and its using the dragonlink configurar to
do all the settings
