### ISSUE TITLE
KKC cannot connect to V2 FC

### ISSUE THREAD

**Issue by buzkill420** [fedorcomander/kkc#4]
i have both an older v1 and a newer v2, and i have no issue connecting the v1 to the kkc. V2 will not connect.  Connects to pc fine, so i know usb is good.  Not sure what else to try. 

Cheers.

**Comment by fedorcomander** [comment]
1. what fw on kkc / fc?
2. does blue led stops blinking when u connect?

**Comment by buzkill420** [comment]
No.  Keeps flashing.

Firmware KISSFCV2F7-1.3-RC45y

And newest kkc 1.27.3

**Comment by fedorcomander** [comment]
try to reverse usb cable (or check where host side goes, and where device side goes)

**Comment by buzkill420** [comment]
I've tried that.  All combos. And like i said,  no issue with my v1 in any configuration.  Thanks for fast reply btw! 👍

**Comment by fedorcomander** [comment]
v1 and v2 use different drivers on kkc side. so they are different. can u make small video when u connecting kkc to fc and all wires visible.

also have u tried with FC powered from lipo?

**Comment by buzkill420** [comment]
I've actually ONLY been able to connect with the lipo plugged into the v1 drone (no battery on kkc needed)  but does not work with kkc battery.  . Will make short video now.  Cheers

**Comment by buzkill420** [comment]
https://youtu.be/irPo7vmE6pE

**Comment by fedorcomander** [comment]
first of all. u dont need to power quad from lipo. 

powering from flight controller is NOT NORMAL. its a bug in v1 fc.


power kkc. then plug to fc.

try to rotate that small usb cable that goes from kkc to usb adapter.

**Comment by buzkill420** [comment]
Rotating cord makes no difference.  And you say i don't need to power the fc from lipo, well if that's the case,  then both fc will not connect with battery only plugged to kkc. Maybe my otg cable isnt working.  Not sure how it would work with quad powered though and not the other way around.  Will get a new otg cable and try with that

**Comment by fedorcomander** [comment]
solved? put something for others pls!

---
Cheers,
Alex

**Comment by fedorcomander** [comment]
yes. fc should get power from kkc. 

---
Cheers,
Alex

**Comment by buzkill420** [comment]
Got new otg adaptor and works flawlessly.  Thanks again!

**Comment by fedorcomander** [comment]
cool!

---
Cheers,
Alex
